### ISSUE TITLE
Support Kafka 0.9.0.0？

### ISSUE THREAD

**Issue by Muyoo** [yahoo/kafka-manager#189] opened 2016-01-20 03:59 UTC
Kafka's latest version is 0.9.0.0. Is there any plan to support this new version? 
I've installed Kafka Manager and choose to control 0.8.2.1(my Kafka is 0.9.0.0). However, when i create topics or delete topics, it will fail.

**Comment by aadrian** [comment] 2016-01-20 09:36
duplicate of  #163

**Comment by mindscratch** [comment] 2016-02-11 17:01
@aadrian I think this might be related, but isn't a duplicate (since this has to do with creating/deleting topics).

**Comment by aadrian** [comment] 2016-02-11 17:56
@mindscratch the title is the same, and I understand with "support for 0.9.0.0" **all** operations. A partially working manager is useless.

**Comment by patelh** [comment] 2016-02-12 06:15
@Muyoo I just tried this on my local machine and I am able to create and delete topics fine with 0.9.0.0.  Do you have security enabled ?  One of the biggest changes with 0.9.0.0 is security and that will need some work to add to KM.

**Comment by patelh** [comment] 2016-02-15 06:00
#195 adds support for 0.9.0.0 but I am not able to duplicate your scenario where you weren't able to add or delete topics.  We don't support security right now so if you had security enabled then it would not work.

**Comment by Muyoo** [comment] 2016-02-23 02:51
@patelh I don't think I set the security enabled. I will try #195 . Thank you very much!
Here is my configures. Hope it will be helpful. 

_broker.id=3

delete.topic.enable=true

auto.create.topics.enable=false

listeners=PLAINTEXT://:9092

advertised.host.name=192.168.100.215

num.network.threads=3
 
num.io.threads=8

socket.send.buffer.bytes=102400

socket.receive.buffer.bytes=102400

socket.request.max.bytes=104857600

log.dirs=/home/kafka/data/

num.partitions=1

num.recovery.threads.per.data.dir=1

log.retention.hours=168

log.segment.bytes=1073741824

log.retention.check.interval.ms=300000

log.cleaner.enable=false

zookeeper.connect=tb-200:2181,tb-205:2181,tb-210:2181

zookeeper.connection.timeout.ms=6000_

**Comment by xuwei-k** [comment] 2016-03-25 05:16
https://github.com/yahoo/kafka-manager/pull/195

**Comment by patelh** [comment] 2016-03-26 20:56
This has been merged into master and released as tag 1.3.0.7

**Closed by patelh** 2016-03-26 20:56 UTC

**Comment by bmillemathias** [comment] 2016-03-27 06:58
https://github.com/yahoo/kafka-manager/issues/163 can be closed as well
