### ISSUE TITLE
support for kafka 0.10

### ISSUE THREAD

**Issue by dmead** [yahoo/kafka-manager#260] opened 2016-07-01 23:19 UTC
will kafka-manager support kafka 0.10?

**Comment by g10ck** [comment] 2016-07-05 15:47
Same question

**Comment by KulikovaLidia** [comment] 2016-07-05 15:51
+1

**Comment by jose9r** [comment] 2016-07-05 16:09
+2 !!!!!

**Comment by phillipamann** [comment] 2016-07-05 23:19
+1 👍

**Comment by Raboo** [comment] 2016-07-06 11:45
There is already a issue for this  #238.

**Comment by sabarishs** [comment] 2016-07-07 04:06
+1

**Comment by minhdanh** [comment] 2016-07-08 06:53
+1

**Comment by dpoldrugo** [comment] 2016-07-09 08:38
+1

**Comment by jantoniucci** [comment] 2016-07-10 22:25
+1

**Comment by patelh** [comment] 2016-07-11 05:51
Closing this as duplicate of #238

**Closed by patelh** 2016-07-11 05:51 UTC
